### ISSUE TITLE
nonce_fast.py throw an error

### ISSUE THREAD

**Issue by mmitech** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#8]
I get this when nonce_fast.py is trying to check the work of a found block:

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/netis/pyethereum/ethereum/nonce_fast.py", line 35, in worker
    result = ethpow.check_pow(block_number, header_hash, mixhash, nonce, difficulty)
  File "/usr/local/lib/python2.7/dist-packages/repoze.lru-0.6-py2.7.egg/repoze/lru/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 70, in check_pow
    cache = get_cache(block_number)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 46, in get_cache
    c = cache_by_seed.pop(seed)  # pop and append at end
  File "/usr/lib/python2.7/collections.py", line 140, in pop
    del self[key]
  File "/usr/lib/python2.7/collections.py", line 69, in __delitem__
    link_prev, link_next, _ = self.__map.pop(key)
KeyError: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/netis/pyethereum/ethereum/nonce_fast.py", line 35, in worker
    result = ethpow.check_pow(block_number, header_hash, mixhash, nonce, difficulty)
  File "/usr/local/lib/python2.7/dist-packages/repoze.lru-0.6-py2.7.egg/repoze/lru/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 70, in check_pow
    cache = get_cache(block_number)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 46, in get_cache
    c = cache_by_seed.pop(seed)  # pop and append at end
  File "/usr/lib/python2.7/collections.py", line 140, in pop
    del self[key]
  File "/usr/lib/python2.7/collections.py", line 69, in __delitem__
    link_prev, link_next, _ = self.__map.pop(key)
KeyError: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/netis/pyethereum/ethereum/nonce_fast.py", line 35, in worker
    result = ethpow.check_pow(block_number, header_hash, mixhash, nonce, difficulty)
  File "/usr/local/lib/python2.7/dist-packages/repoze.lru-0.6-py2.7.egg/repoze/lru/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 70, in check_pow
    cache = get_cache(block_number)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 46, in get_cache
    c = cache_by_seed.pop(seed)  # pop and append at end
  File "/usr/lib/python2.7/collections.py", line 140, in pop
    del self[key]
  File "/usr/lib/python2.7/collections.py", line 69, in __delitem__
    link_prev, link_next, _ = self.__map.pop(key)
KeyError: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/netis/pyethereum/ethereum/nonce_fast.py", line 35, in worker
    result = ethpow.check_pow(block_number, header_hash, mixhash, nonce, difficulty)
  File "/usr/local/lib/python2.7/dist-packages/repoze.lru-0.6-py2.7.egg/repoze/lru/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 70, in check_pow
    cache = get_cache(block_number)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 46, in get_cache
    c = cache_by_seed.pop(seed)  # pop and append at end
  File "/usr/lib/python2.7/collections.py", line 140, in pop
    del self[key]
  File "/usr/lib/python2.7/collections.py", line 69, in __delitem__
    link_prev, link_next, _ = self.__map.pop(key)
KeyError: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/netis/pyethereum/ethereum/nonce_fast.py", line 35, in worker
    result = ethpow.check_pow(block_number, header_hash, mixhash, nonce, difficulty)
  File "/usr/local/lib/python2.7/dist-packages/repoze.lru-0.6-py2.7.egg/repoze/lru/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 70, in check_pow
    cache = get_cache(block_number)
  File "/home/netis/pyethereum/ethereum/ethpow.py", line 46, in get_cache
    c = cache_by_seed.pop(seed)  # pop and append at end
  File "/usr/lib/python2.7/collections.py", line 140, in pop
    del self[key]
  File "/usr/lib/python2.7/collections.py", line 69, in __delitem__
    link_prev, link_next, _ = self.__map.pop(key)
KeyError: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
````

Any ideas what is wrong here ?

**Comment by karek314** [comment]
It shouldn't matter._** ethpow.check_pow**_ is called many times, it appears sometimes one or more of them may fail. Maybe try adjust thread number to fit your hardware specs.
